#! /usr/bin/env bash

set +x

prep_home() {
    
    if ! command -v home-manager &> /dev/null
    then
	    echo "HomeManager not found, creating ..."
        # home manager files
        nix-channel --add https://github.com/nix-community/home-manager/archive/release-22.05.tar.gz home-manager
        nix-channel --update
        nix-shell '<home-manager>' -A install
    fi

	echo "Copying files ..."
	mkdir -p $HOME/.config/nixpkgs/home
	cp ./home.nix $HOME/.config/nixpkgs/
	cp -r ./home/* $HOME/.config/nixpkgs/home/
    cp ./system/vimrc $HOME/.config/nixpkgs/home/
}

bsystem() {
    echo "buiding system, arguments: $@"

	sudo nix-channel --add https://nixos.org/channels/nixos-23.11 nixos
	sudo nix-channel --update

    sudo mkdir -p /etc/nixos/system
	sudo cp configuration.nix /etc/nixos/

    sudo cp -r ./system/. /etc/nixos/system
	sudo nixos-rebuild switch $@
}

bhome() {
	prep_home
    echo "buiding home, arguments: $@"
	home-manager switch $@
}

all() {
    echo "buiding system and home, arguments: $@"
#	bsystem $@ && bhome $@
    sudo nixos-rebuild switch --flake .\#FW-i11
}

case $1 in 
	"home")
		bhome ${@:2};;
	"system")
		bsystem ${@:2};;
	*)
        all ${@:2};;
esac
