live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.normal]
black = "0x2c2525"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Blex Mono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Blex Mono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Blex Mono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Blex Mono Nerd Font Mono"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true

[window.dimensions]
columns = 120
lines = 35
