" You might have to force true color when using regular vim inside tmux as the
" colorscheme can appear to be grayscale with "termguicolors" option enabled.
" vim-only 
"if !has('gui_running') && &term =~ '^\%(screen\|tmux\)'
"  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
"  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
"endif
set termguicolors
set mouse=a
"set mousehide
"
" filetype plugin indent on
syntax on
set nocompatible

set sidescroll=10

"set ambiwidth=double

set cursorline
set visualbell
"set belloff=all
set showcmd

highlight Comment cterm=italic

set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8

"set title
"set titleold="Terminal"
"set titlestring=%F


set statusline=%F%m%r%h%w%=(%{&ff}/%Y)\ (line\ %l\/%L,\ col\ %c)\

"" Disable the blinking cursor.
set gcr=a:blinkon0
set scrolloff=3

"" Status bar
set laststatus=2

colorscheme default

"" Fix backspace indent
set backspace=indent,eol,start

"set number
"set relativenumber
"

set autoindent
set smartindent

set textwidth=80
set colorcolumn=80
nnoremap \cc :set colorcolumn=80<cr>
nnoremap \ncc :set colorcolumn-=80<cr>


"set smarttab
"" Tabs. May be overridden by autocmd rules
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set splitright
set splitbelow


"" Map leader to '',
let mapleader= " "

"" Enable hidden buffers
set hidden


set nobackup
set nowritebackup
set autoread
set noswapfile

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

set clipboard+=unnamedplus

nnoremap n nzzzv
nnoremap N Nzzzv

set fileformats=unix,dos,mac

"*****************************************************************************
"" Abbreviations
"*****************************************************************************
"" no one is really happy until you have this shortcuts
cnoreabbrev Q q
cnoreabbrev Q! q!
cnoreabbrev Qall qall
cnoreabbrev Qall! qall!
cnoreabbrev W w
cnoreabbrev W! w!
cnoreabbrev WQ wq
cnoreabbrev Wa wa
cnoreabbrev Wq wq
cnoreabbrev wQ wq

"" Buffer movements
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>

" save as sudo
cmap w!! w !sudo tee > /dev/null %

"save undo / redo across sessions
set undofile
set undodir=~/.vim/undo

" treat underscore (_) as a word 
"set iskeyword+=_
"

"" Sensible Nav -- no longer needed because for the tmux-nav 
"nnoremap <C-J> <C-W><C-J>
"nnoremap <C-K> <C-W><C-K>
"nnoremap <C-L> <C-W><C-L>
"nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright

" Finding Files:
" Search down into subfolders

"better wildmenu
set path+=**
set wildmenu
set wildmode=longest:list,full

command! MakeTags !ctags -R .

if executable("rg")
    set grepprg=rg\ --vimgrep\ --smart-case\ --hidden
    set grepformat=%f:%l:%c:%m
endif

"set gp=git\ grep\ -n

" File browser:
"let g:netrw_banner=0
"let g:netrw_browse_split=4
"let g:netrw_altv=1
"let g:netrw_liststyle=3
"let g:netrw_list_hide=netrw_gitignore#Hide()


