# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/298eb0ad-cbf8-48fd-91d8-2225b43cd7fa";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EBC1-B516";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0c2042a7-58c8-4b00-a463-904465593a0f"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics.enable = true;
  services.fwupd.enable = true;

  powerManagement.enable = true;
  #services.tlp = {
  #    enable = true;
  #    settings = {
  #        PCIE_ASPM_ON_BAT = "powersupersave";
  #        CPU_SCALING_GOVERNOR_ON_AC = "performance";
  #        CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
  #        START_CHARGE_THRESH_BAT1 = 90;
  #        STOP_CHARGE_THRESH_BAT1 = 97;
  #        RUNTIME_PM_ON_BAT = "auto";
  #    };
  #};

  services.thermald = {
    enable = true;
  };
}
